textdraw_text_max_len = 50
blur_sigma = 1.0
colorfill_image_size = 256
allow_local_file_input = false

[[textdraws]]
name = "pupil"
filename = "config/images/pupil.jpg"
mids = [ [ 140, 325,],]
color = [ 0, 0, 0,]
scale = [ 50, 50,]
font = "config/fonts/Impact.ttf"
max_width = 13

name="drake"
filename="config/images/Drake.jpg"
mids = [ [ 900, 300,], [900, 900,],]
color = [0, 0, 0,]
scale = [90, 90,]
font = "config/fonts/Impact.ttf"
max_width = 13

name="changemymind"
filename="config/images/Change-My-Mind.jpg"
mids = [ [320, 250,],]
color = [0, 0, 0,]
scale = [20,20,]
font = "config/fonts/Impact.ttf"
max_width = 23

name="truthscroll"
filename="config/images/Scroll-of-Truth.jpg"
mids = [ [348, 850,],]
color = [0, 0, 0,]
scale = [40,40,]
font = "config/fonts/HiMelody-Regular.ttf"
max_width = 10


[[overlays]]
name = "wanted"
filename = "config/images/wanted.jpg"
coords = [ 80, 181,]
resize = [ 340, 340,]
input_size = 256

